name: Auto Merge Approved PRs

on:
  pull_request_review:
    types: [submitted]

jobs:
  auto-merge:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - name: Auto-merge PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.payload.pull_request.number;
            const repo = context.repo.repo;
            const owner = context.repo.owner;

            const { data: pr } = await github.pulls.get({
              owner,
              repo,
              pull_number: prNumber
            });

            if (pr.mergeable_state === 'clean') {
              await github.pulls.merge({
                owner,
                repo,
                pull_number: prNumber,
                merge_method: 'squash'
              });
              console.log(`PR #${prNumber} merged.`);
            } else {
              console.log(`PR #${prNumber} not mergeable.`);
            }
